### PR TITLE
Add pipeline for gcext test

### LINKED ISSUE #256: Buildkite is not running `gcext` test
Similar to embedding these are tests that need to run manually.

x-ref https://github.com/JuliaLang/julia/pull/47699

### LINKED ISSUE #258: Buildkite is not running the embedding tests
Reported by @vchuravy on Slack

### PR DESCRIPTION
**Pull request by vchuravy**
Fixes #256
Fixes #258

### CODE REVIEW

**Comment by vchuravy** [comment]
@DilumAluthge can we make this allow-fail first?

**Comment by DilumAluthge** [comment]
FYI, for any job that we mark as "soft fail", I prefer that we also put that job under the "Allow Fail" group. Then, all the "soft fail" jobs appear in a single place (the "Allow Fail" group) in the Buildkite web UI.

**Comment by DilumAluthge** [comment]
You also need to move the pipeline launch to be located with the other "allow fail" jobs. I'll push to this branch.

**Comment by vchuravy** [comment]
Good to merge? Will need https://github.com/JuliaLang/julia/pull/47699 to be working.

**Pull request merged**
