### PR TITLE
Prevent some "launch jobs" jobs from running on pibots

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
cc: @topolarity

**Review by fredrikekre — APPROVED** [review]

**Comment by topolarity** [comment]
Should we do the same for "Test" and "Check"?

**Comment by topolarity** [comment]
> Should we do the same for "Test" and "Check"?

I guess that's not really necessary, since the other jobs don't use Julia

**Comment by DilumAluthge** [comment]
Yeah, it's the need to install Julia that causes problems on the pibots.

**Pull request merged**
