### PR TITLE
Try fixes to base codecov

### PR DESCRIPTION
**Pull request by IanButterworth**
Trying out https://github.com/JuliaLang/julia/pull/46403

TODO before merging:
- [ ] In `pipelines/scheduled/coverage/coverage.yml`, delete line 8 and uncomment line 9.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
You also need to comment out this line: https://github.com/JuliaCI/julia-buildkite/blob/7154428640aa14529feaee169895571719b72af7/pipelines/scheduled/coverage/coverage.yml#L8

When you do so, it can be helpful to put a TODO in the PR description so that we don't forget to uncomment that line before we merge the PR.

**Comment by DilumAluthge** [comment]
I'll re-generate the signature.

**Comment by DilumAluthge** [comment]
> I'll re-generate the signature.

Done.

**Comment by IanButterworth** [comment]
Replaced by #277

**Pull request closed without merging**
