### PR TITLE
mark revise and gcext as not soft failable

### PR DESCRIPTION
**Pull request by KristofferC**
Too easy to miss these and merge breaking code otherwise.

### CODE REVIEW

**Comment by giordano** [comment]
Partial duplicate of  #393

**Comment by DilumAluthge** [comment]
After https://github.com/timholy/Revise.jl/pull/856 is merged, do we also need to wait for a new release of Revise to be registered?

Or does `test-revise` run on `Revise#master`?

**Comment by KristofferC** [comment]
Master it seems:

https://github.com/JuliaCI/julia-buildkite/blob/4821ba2a04c24c578f20faf98c427e189f450bfa/pipelines/main/misc/test_revise.yml#L33

**Comment by topolarity** [comment]
Any reason for closing?

**Comment by KristofferC** [comment]
I didn't see https://github.com/JuliaCI/julia-buildkite/pull/393 was closed heh

**Review by DilumAluthge — APPROVED** [review]

**Pull request merged**
