### PR TITLE
Only run the Apple Silicon tester if the branch is `master` or `main`

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by staticfloat** [comment]
Why don't we try just running it on `master` for now?  That should cut down the testing burden significantly.  I still want to see the results of the tests.

**Comment by DilumAluthge** [comment]
Ugh that's not right.... we only want to apply this change to the Apple Silicon tester; we don't want to apply it to the x86_64 tester.

**Comment by DilumAluthge** [comment]
I was hoping to use Buildkite conditionals, but I don't think we can do that here, since we also need to condition on the arch.

**Comment by DilumAluthge** [comment]
@staticfloat Is there any way to debug Buildkite conditionals? I'd like to print what the value of `build.env("ARCH")` actually is.

**Comment by staticfloat** [comment]
It looks to me like you do need quotes: https://buildkite.com/docs/pipelines/conditionals#example-expressions

**Comment by DilumAluthge** [comment]
Yeah, that's what I had thought. Buildkite support told me in email to try it without the quotes. I just replied to their email with a link to the latest log.

**Comment by DilumAluthge** [comment]
I CC'd you on my reply.

**Pull request closed without merging**
