### PR TITLE
Build for `x86_64-linux-gnu` with `-Werror`

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Review by DilumAluthge — CHANGES_REQUESTED** [review]
Can you also add it to line 4? (The `x86_64-linux-gnuassert` job.)

**Review by DilumAluthge — APPROVED** [review]

**Comment by giordano** [comment]
The musl build has a warning.  I wanted to copy it here for my own record, but it looks like copying from the log is quite broken.  The warning is about `_POSIX_C_SOURCE` being undefined in `src/signals-unix.c`

**Comment by DilumAluthge** [comment]
> I wanted to copy it here for my own record, but it looks like copying from the log is quite broken.

FWIW, I will first copy from the Buildkite website into a text editor (e.g. Atom), and then I'll copy from the text editor into GitHub.

**Comment by giordano** [comment]
That worked, thanks
```
In file included from /cache/build/dockerized-amdci4-6/julialang/julia-buildkite/src/signal-handling.c:169:
/cache/build/dockerized-amdci4-6/julialang/julia-buildkite/src/signals-unix.c: In function 'signal_listener':
/cache/build/dockerized-amdci4-6/julialang/julia-buildkite/src/signals-unix.c:751:5: warning: "_POSIX_C_SOURCE" is not defined, evaluates to 0 [-Wundef]
  751 | #if _POSIX_C_SOURCE >= 199309L
      |     ^~~~~~~~~~~~~~~
```

**Pull request merged**
