### PR TITLE
Add windows build

### PR DESCRIPTION
**Pull request by staticfloat**
After integrating the great work done by @inkydragon in https://github.com/JuliaCI/julia-buildkite/issues/25 into https://github.com/JuliaCI/rootfs-images/pull/227 and running https://github.com/JuliaCI/sandboxed-buildkite-agent/pull/22 we are ready to try this out.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@staticfloat Instead of pulling the Docker image by the `v*.*` tag, what do you think about pulling by the sha256 digest (which can be found at the bottom of the CI logs)?

**Comment by staticfloat** [comment]
I think that makes it much more difficult to, at a glance, figure out what version we're actually using.  Why wouldn't you want to use the tag name?

**Comment by DilumAluthge** [comment]
> I think that makes it much more difficult to, at a glance, figure out what version we're actually using. Why wouldn't you want to use the tag name?

Only that digests are immutable and tags are mutable. So it protects us from breaking CI by accidentally pushing to the same tag.

That would be an unlikely event, though, so preventing it might not be worth the loss of readability.

**Comment by staticfloat** [comment]
Yeah; even if we did push to the same tag, it would just download the new image, which IMO is not that big of a deal.  If we didn't control the images that are being pushed up to docker hub, I would be more interested in this, but since we control it, I figure using the human-readable name is best.

**Comment by staticfloat** [comment]
Uhghhhhh the win32 compiler uses the wrong exception model.  It's linking against `libgcc_s_dw2-1.dll`.

**Comment by staticfloat** [comment]
With a new compiler, and some massaging, we've got builds that are running tests!  Some things to look into:

- [ ] `SystemError: GetClipboardData: Invalid clipboard format`: [Example](https://buildkite.com/julialang/julia-buildkite/builds/952#01836695-a144-48ea-a452-23665617dbb7/358-817).  Possbily some consequence of [how we're starting the buildkite agent](https://github.com/JuliaCI/sandboxed-buildkite-agent/blob/8567e1a2d18ae0b0a371f20d1a8f878d9e242922/windows-kvm/buildkite-worker/setup_scripts/0-02-install-buildkite-agent.ps1#L12-L16) in a headless fashion?
- [ ] `A "spawn and wait lots of tasks" test failed`: [Example](https://buildkite.com/julialang/julia-buildkite/builds/952#01836695-a144-48ea-a452-23665617dbb7/358-967).  Sounds like a segfault, but unsure why.

**Comment by DilumAluthge** [comment]
> * We should disable things that rely on backtraces on win32, such as the `Profile` test, since that is extremely slow there.

cc: @ianbutterworth, who may have some hints/tips for us here.

**Comment by staticfloat** [comment]
I think this is good to go!  @DilumAluthge want to take a quick look over it?

**Review by DilumAluthge — APPROVED** [review]
So the build runs inside Docker, but the tests do not? Any particular reason for this?

Otherwise LGTM. Agree with leaving the tests as "allow fail" initially.

**Comment by staticfloat** [comment]
> So the build runs inside Docker, but the tests do not? Any particular reason for this?

Because we don't need (and indeed, don't want) any compilers around for the tests.  There's enough basic utilities available in the base image that we don't need a docker image for the tests.

**Review by DilumAluthge — APPROVED** [review]

**Pull request merged**
