### PR TITLE
Upload on PR builds as well

### PR DESCRIPTION
**Pull request by staticfloat**
This is a follow-up to c8b470989226b3a8f8d4874268ccbee616da2ebf, I forgot that we elide the upload jobs completely when not on `master` or `release-*`.  This remediates the situation, uploading PR builds as well.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
So, with this PR, we'll start uploading all PR builds to S3, right?

Our S3 usage is going to increase by a not-insignificant amount. Is that a concern?

**Comment by staticfloat** [comment]
> Our S3 usage is going to increase by a not-insignificant amount. Is that a concern?

It will probably increase our monthly bill by $200-300.  It's not too bad.

**Comment by DilumAluthge** [comment]
Should we also have an S3 lifecycle rule to automatically delete PR builds after `N` days?

**Comment by staticfloat** [comment]
All builds uploaded to the nightlies bucket are deleted after 60 days.

**Review by DilumAluthge — DISMISSED** [review]

**Review by DilumAluthge — DISMISSED** [review]

**Review by DilumAluthge — APPROVED** [review]

**Pull request merged**
