### PR TITLE
Promote `test i686-linux-gnu[net]` and `gcext` to must-pass

### PR DESCRIPTION
**Pull request by IanButterworth**
- Promotes `test i686-linux-gnunet` and `test i686-linux-gnu`
- Promotes `gcext`

Closes https://github.com/JuliaCI/julia-buildkite/issues/325

### CODE REVIEW

**Comment by IanButterworth** [comment]
Something's not right here with gcext now
```

2024-06-21 10:03:34 EDT | /cache/build/builder-amdci5-2/julialang/julia-buildkite/test/gcext/gcext.c:7:10: fatal error: julia_gcext.h: No such file or directory
-- | --
  | 2024-06-21 10:03:34 EDT | 7 \| #include "julia_gcext.h"
  | 2024-06-21 10:03:34 EDT | \|          ^~~~~~~~~~~~~~~
  | 2024-06-21 10:03:34 EDT | compilation terminated.


```

**Comment by IanButterworth** [comment]
Oh, right, it's broken in the same way on julia master https://buildkite.com/julialang/julia-master/builds/37576#0190388d-d5b8-4dcb-8359-b6c1841a3aaa

**Comment by IanButterworth** [comment]
Same failure twice in a row on `test i686-linux-gnu`

```
  | 2024-06-21 13:47:24 EDT | misc                                             (10) \|         failed at 2024-06-21T17:47:24.853
  | 2024-06-21 13:47:24 EDT | Test Failed at /cache/build/tester-amdci5-10/julialang/julia-buildkite/julia-01af3e921f/share/julia/test/misc.jl:590
  | 2024-06-21 13:47:25 EDT | Expression: abs(summarysize(z) - 640000) / 640000 <= 0.01
  | 2024-06-21 13:47:25 EDT | Evaluated: 0.18746875 <= 0.01
  | 2024-06-21 13:47:25 EDT
```

**Comment by IanButterworth** [comment]
Blocked by https://github.com/JuliaLang/julia/pull/54606#issuecomment-2183664446

**Comment by IanButterworth** [comment]
Seems like this intermittent issue should also be a blocker https://github.com/JuliaLang/julia/issues/54450

**Comment by vtjnash** [comment]
We can mark that test_skip or `@test skip=true` as that test has never worked correctly on i686 (but we missed out on that because it wasn't a must-pass test)

**Comment by IanButterworth** [comment]
Hit another failure now

```

math                                              (7) |         failed at 2024-06-23T13:58:26.792
Test Failed at /cache/build/tester-amdci5-8/julialang/julia-buildkite/julia-2d4ef8a238/share/julia/test/math.jl:1607
  Expression: Core.Compiler.is_foldable(effects)
     Context: effects = (+c,+e,+n,!t,+s,+m,+u,+o)
              T = Float64

```

**Comment by IanButterworth** [comment]
https://github.com/JuliaLang/julia/pull/54910

**Pull request merged**
