### PR TITLE
Disable `-Wunused-but-set-variable` on `aarch64-apple-darwin`

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by giordano** [comment]
If there's only a warning, how about disabling only that?

**Comment by DilumAluthge** [comment]
Do we need to change the format of the `MAKE_FLAGS` column? Right now, the entries in `MAKE_FLAGS` are comma-separated, but obviously this will be a problem if the entries themselves contain commas.

**Comment by staticfloat** [comment]
Actually, I don’t want a comma I want a space. I just havent figured out how to do it yet. :P

**Comment by giordano** [comment]
I presume you already tried quotes?

**Comment by staticfloat** [comment]
I struggled for about half an hour trying to shoe-horn multiple values into the `JL_CFLAGS` make flag here, and couldn't do it.  I'm just going to merge a lack of `-Werror` and we can improve things later.

**Pull request merged**
