### PR TITLE
Add builder and tester for PowerPC with asserts; ppc64le-linux-gnuassert

### PR DESCRIPTION
**Pull request by ahsansaghir**
This PR adds pipeline for builder and tester for PowerPC with asserts enabled (for both Julia and LLVM).

### CODE REVIEW

**Comment by staticfloat** [comment]
I think `-Werror` might be a little bit ambitious.  ;)

If you want to experiment with your own branch of Julia, you can (temporarily) modify [these lines](https://github.com/JuliaCI/julia-buildkite/blob/bc92933c788311c33204b505a459932b15462be9/.buildkite/hooks/post-checkout#L7-L8) to fetch your own version of Julia and run the tests on this PR; that will allow you to iterate on any changes needed in Julia while modifying this code.

If you're going to be iterating a lot, please comment out the other build jobs so that you're only building ppc64le over and over again.  :)

**Comment by ahsansaghir** [comment]
> I think `-Werror` might be a little bit ambitious. ;)
> 
> If you want to experiment with your own branch of Julia, you can (temporarily) modify [these lines](https://github.com/JuliaCI/julia-buildkite/blob/bc92933c788311c33204b505a459932b15462be9/.buildkite/hooks/post-checkout#L7-L8) to fetch your own version of Julia and run the tests on this PR; that will allow you to iterate on any changes needed in Julia while modifying this code.
> 
> If you're going to be iterating a lot, please comment out the other build jobs so that you're only building ppc64le over and over again. :)

Yeah, I did not realize that `-Werror` would be ambitious. :). Thanks a lot for the tips! I will iterate over without `-Werror` and see how it goes. :)

**Comment by ahsansaghir** [comment]
@staticfloat This PR is now ready for review. Regarding `rr`; I discussed with Valentin and it seems like it would be very hard to get `rr` working on PPC. It requires the use of precise performance counters and apparently the ones that are needed aren't precise enough on PPC9.

I have divided formatting and actual changes into two commits to make it easier to compare the actual changes.

**Comment by ahsansaghir** [comment]
FYI @vchuravy. This is the PR that I have put up for adding the builder/tester for PowerPC with asserts enabled.

**Review by staticfloat — APPROVED** [review]
This looks good to me!  Thanks for pushing this through, @ahsansaghir!

Do you think that these assert builds will be somewhat temporary, (as we intend to crush the PPC-specific bugs in the near term) or do you think we should keep them forever?

**Comment by vchuravy** [comment]
I think we should keep them permanently, I think we undertest non x86,

**Pull request merged**
