### PR TITLE
Add `powerpc64le-linux-gnu` builder, tester and uploader

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by staticfloat** [comment]
Failure is https://github.com/JuliaLang/julia/issues/45019, will wait for packaging at least to be fixed before merging.

**Comment by DilumAluthge** [comment]
@staticfloat Can you update the signatures before merging?

**Comment by staticfloat** [comment]
@vchuravy I'm explicitly testing your branch here.

**Comment by vchuravy** [comment]
LGTM!

**Pull request merged**
