### PR TITLE
Demote the musl builder (`build x86_64-linux-musl`) to "allow fail" (`soft-fail`)

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaCI/julia-buildkite/issues/321

The musl tester was already "allow fail", so this PR just demotes the musl builder (and the musl uploader) to "allow fail".

### CODE REVIEW

**Comment by staticfloat** [comment]
@DilumAluthge apparently we've never had soft fails on builds before, because the upload job fails after the build fails. :P

Can you work out a solution here?  Either preventing the upload job from running if the build fails, or something else?

**Comment by DilumAluthge** [comment]
Can we mark the musl upload job as soft-fail?

**Comment by DilumAluthge** [comment]
> Can we mark the musl upload job as soft-fail?

Done in https://github.com/JuliaCI/julia-buildkite/pull/324/commits/d591e3e57a3fd95607ec592ad493a4420ac44129

@staticfloat @IanButterworth Can you review?

**Comment by DilumAluthge** [comment]
@staticfloat Can you re-sign the pipelines?

**Comment by DilumAluthge** [comment]
@staticfloat Can you re-sign the pipelines?

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
Ugh I forgot one place.

**Comment by DilumAluthge** [comment]
@staticfloat Can you re-sign again? I had to fix one last thing.

**Comment by DilumAluthge** [comment]
@staticfloat I think you lost my changes in https://github.com/JuliaCI/julia-buildkite/commit/d591e3e57a3fd95607ec592ad493a4420ac44129 😭

**Comment by DilumAluthge** [comment]
Looks like my changes from https://github.com/JuliaCI/julia-buildkite/commit/8da2caf5f7c62a7c0ab3e0c834923b91cdbbbde6 were lost

**Comment by giordano** [comment]
Usual reminder to use `--force-with-lease` instead of `--force`

**Pull request merged**
