### PR TITLE
Linux: increase the timeout for the "net" (Pkg and friends) tests

### PR DESCRIPTION
**Pull request by DilumAluthge**
Ref #320

### CODE REVIEW

**Comment by DilumAluthge** [comment]
cc: @vtjnash

Ref #320

**Comment by DilumAluthge** [comment]
@staticfloat Any idea why some of the Windows jobs are failing on this PR?

**Comment by staticfloat** [comment]
No, looks like a Documenter error.  @mortenpi

**Comment by mortenpi** [comment]
Yes, that's a failure in `doc/make.jl`, and might have to do something with path handling. But it seems to work fine on master? https://buildkite.com/julialang/julia-master/builds/32905#018d5bbd-3469-4972-aa89-0dfaf544c5b4/22353-22445

**Comment by staticfloat** [comment]
My guess is it’s not happy with how this repository is a different git repo?

**Comment by mortenpi** [comment]
> My guess is it’s not happy with how this repository is a different git repo?

Yea, this seems plausible. I see that there's a difference in the third `git clone` that I can see in the logs. In this repo:

```
git clone -v --dissociate --reference C:\\cache\\repos\\https---github-com-JuliaCI-julia-buildkite-git -- https://github.com/JuliaCI/julia-buildkite.git .
```

vs

```
git clone -v --dissociate --reference C:\\cache\\repos\\https---github-com-JuliaLang-julia-git -- https://github.com/JuliaLang/julia.git .
```

But where is the Julia source code coming from in the former case?

**Comment by KristofferC** [comment]
Can this be merged anyway to allow for https://github.com/JuliaLang/julia/pull/53125 to be unblocked.

**Pull request merged**
