### PR TITLE
Run a selected subset of tests under ASAN

### PR DESCRIPTION
**Pull request by tkf**
Applying https://github.com/JuliaLang/julia/pull/44546 here.

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]
Assuming CI passes, this seems good to me.

**Comment by DilumAluthge** [comment]
cc: @timholy

**Comment by DilumAluthge** [comment]
We should probably increase the timeout?

It's unfortunate that it takes so long...

**Comment by timholy** [comment]
If this isn't feasible, no sweat. I wondered if doing more than just build might catch some bugs. Of the CI failures, I'm not sure about many of them, but the ` LoadError: could not load library "libjulia-codegen"` might be an `so` filename issue?

**Comment by tkf** [comment]
That's probably because the codgen tests are not written for `julia-debug`. There's only `libjulia-codegen-debug.so` etc. in this build.

**Review by DilumAluthge — APPROVED** [review]

**Pull request merged**
