### PR TITLE
Update Windows codesigning for scheduled build

### LINKED ISSUE #406: Upload x86_64-w64 failed every time
This task always seems to fail.

https://buildkite.com/julialang/julia-master-scheduled/builds?branch=master

```
Preparing Setup program executable
   Updating icons (SETUP.E32)
   Updating version info (SETUP.E32)
   Running Sign Tool mysigntool: bash.exe '/c/workdir/.buildkite/utilities/windows/codesign.sh' "C:\workdir\uninst.e32.tmp"
   ERROR: Missing AZURE_* secret variables!
   Sign Tool command failed (Sign Tool command failed with exit code 0x1). Will retry (2 tries left).
   Running Sign Tool mysigntool: bash.exe '/c/workdir/.buildkite/utilities/windows/codesign.sh' "C:\workdir\uninst.e32.tmp"
   ERROR: Missing AZURE_* secret variables!
   Sign Tool command failed (Sign Tool command failed with exit code 0x1). Will retry (1 tries left).
   Running Sign Tool mysigntool: bash.exe '/c/workdir/.buildkite/utilities/windows/codesign.sh' "C:\workdir\uninst.e32.tmp"
   ERROR: Missing AZURE_* secret variables!
Error in C:\workdir\.buildkite\utilities\windows\build-installer.iss: Sign Tool command failed with exit code 0x1.
```

https://github.com/JuliaCI/julia-buildkite/blob/0a56a6175a196cea2be0e9d88d480f025cb2f386/utilities/windows/codesign.sh#L51-L56

### PR DESCRIPTION
**Pull request by Zentrik**
Fixes #406.

Copies changes from https://github.com/JuliaCI/julia-buildkite/commit/8a43cc96e67b9c810f6926ca1a1a82ceb81be33a#diff-e3eba28011c21d4b466a1b87b33e4706b7a525b89707c28cbb4757f1d5697694R51 to `upload_windows.yml` to the scheduled build.

### CODE REVIEW

**Comment by Zentrik** [comment]
Looks like someone needs to resign the treehashes.

**Comment by DilumAluthge** [comment]
@Zentrik Can you rebase this PR

**Comment by DilumAluthge** [comment]
@Zentrik Can you rebase this PR against the latest version of the `main` branch, and resolve the merge conflicts?

I can then go in and re-sign the treehashes for the signed pipelines.

**Comment by DilumAluthge** [comment]
Also cc @inkydragon, who did some work on the `scheduled` pipelines recently.

**Comment by DilumAluthge** [comment]
Also cc @staticfloat and @davidanthoff

**Review by staticfloat — DISMISSED** [review]

**Review by IanButterworth — APPROVED** [review]

**Comment by DilumAluthge** [comment]
I'm going to remove the `automerge`, because I want to see the status of `buildkite/julia-buildkite-scheduled` before I merge.

---

Additional explanation:

Currently, the `buildkite/julia-buildkite-scheduled` status is not a "required status check" on this repo. The reason for this is that `buildkite/julia-buildkite-scheduled` has been broken for a long time, and I didn't want to hold up other PRs on this repo, so I removed `buildkite/julia-buildkite-scheduled`` from the list of "required status checks".

On this repo, we use the Kodiak mergebot to automerge PRs. Kodiak only looks at "required status checks". Once all "required status checks" are green, Kodiak will merge the PR, even if there are other status checks that are pending or even failed.

In this case, I'm not quite ready to merge this PR until I see the outcome of `buildkite/julia-buildkite-scheduled`, but if we have the `automerge` label, the Kodiak will merge the PR even if `buildkite/julia-buildkite-scheduled` is still in progress (or has failed).

**Comment by DilumAluthge** [comment]
Alright, all CI checks are green. Let's try this out.

**Comment by DilumAluthge** [comment]
Thank you @Zentrik, @IanButterworth, and @staticfloat!

**Pull request merged**
