### PR TITLE
Add example of using buildkite API in `build_times`

### PR DESCRIPTION
**Pull request by staticfloat**
In trying to figure out if there's any pattern to our slowdown in the
aarch64 mac mini testsuite, I wrote this helper script to aid us in
trying to extract patterns.

To visualize, load the script up, then do something like:

```
 using UnicodePlots

 # Get passing aarch64 mac tests, sort by recency,
 mac_tests_by_time = sort(df[df.key .== "test_aarch64-apple-darwin" .&& df.state .== "passed", :], :date; rev=true)

 # Build colormap for agent name
 agents = sort(collect(Set(mac_tests_by_time[:, :agent])))
 colors = [:green, :blue, :red, :yellow, :cyan, :magenta, :white]
 cmap = Dict(agents[idx] => colors[idx] for idx in 1:length(agents))

 # Plot build number (x) versus duration (y) versus agent (color)
 scatterplot(mac_tests_by_time[:, :elapsed]; marker=:cross, color=[cmap[n] for n in mac_tests_by_time[:, :agent]], width=100)
```

### CODE REVIEW

**Comment by staticfloat** [comment]
Example plot:

image

It seems there is some difference between the MacStadium-hosted mac mini, and the new MIT-hosted mac minis.

**Comment by staticfloat** [comment]
Possible reasons:

- Thermal throttling
- Background processes (not that I can see right now)

**Comment by staticfloat** [comment]
Comparison with `x86-64`:

image

**Comment by staticfloat** [comment]
I just checked and it is the case that `aarch64-macmini-1` has 16GB of RAM, whereas the others have only 8GB.

**Comment by staticfloat** [comment]
Just added another debugging tool; `log_grep.jl`.  Example usage:

```
$ julia --project -i log_grep.jl "httpbingo.org/drip"
[ Info: Requesting page 1
[ Info: Requesting page 2
[ Info: Requesting page 3
[ Info: Requesting page 4
[ Info: Parsing 120 builds...
[ Info: Downloading 3469 logs...
Progress: 100%[==============================================================================================================] Time: 0:01:34
┌ Info: Found matching log!
└   url = "https://buildkite.com/julialang/julia-master/builds/13990#01820a5e-998c-4af1-ae75-26bf5987cb8c"
┌ Info: Found matching log!
└   url = "https://buildkite.com/julialang/julia-master/builds/13952#0182045f-e118-461a-a19b-16429eded8e7"
┌ Info: Found matching log!
└   url = "https://buildkite.com/julialang/julia-master/builds/13952#01820460-071c-4e3d-8aab-84d4eeade674"
...
┌ Info: Found matching log!
└   url = "https://buildkite.com/julialang/julia-master/builds/13548#0181d1ae-fb7a-45b5-ae04-03b0f4c3edd1"
┌ Info: Found matching log!
└   url = "https://buildkite.com/julialang/julia-master/builds/13531#0181cfa8-28d1-47ca-800b-50b6bc8049ce"
┌ Info: Found matching log!
└   url = "https://buildkite.com/julialang/julia-master/builds/13249#0181a0cf-f0b3-4266-97f4-5384f10fcbe8"
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.3 (2022-05-06)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> df
33×9 DataFrame
 Row │ agent                        commit                             date                     elapsed   key                                log_ur ⋯
     │ String                       String                             DateTime                 Float64   String                             String ⋯
─────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1 │ default-amdci4.7             44e9b877e87d65fd6e4d1fb4ed4fb4e5…  2022-07-17T04:15:18.649   3348.37  test_x86_64-linux-musl             https: ⋯
   2 │ default-amdci4.2             6008cbc019424a53786552a511bbef92…  2022-07-16T00:18:48.789   2420.61  test_x86_64-linux-gnu              https:
   3 │ default-amdci4.5             6008cbc019424a53786552a511bbef92…  2022-07-16T00:18:48.789   2146.59  test_x86_64-linux-musl             https:
   4 │ default-macmini-aarch64-4.0  13f65379f869b732c83ba94b6f57200b…  2022-07-15T23:28:27.571   5363.34  test_aarch64-apple-darwin          https:
   5 │ default-amdci4.0             13f65379f869b732c83ba94b6f57200b…  2022-07-15T23:28:27.571   2109.28  test_x86_64-linux-gnu              https: ⋯
   6 │ default-amdci4.6             13f65379f869b732c83ba94b6f57200b…  2022-07-15T23:28:27.571   2099.39  test_i686-linux-gnu                https:
   7 │ default-amdci5.1             13f65379f869b732c83ba94b6f57200b…  2022-07-15T23:28:27.571   1762.89  test_x86_64-linux-musl             https:
   8 │ default-macmini-aarch64-5.0  d117975aa629bee97901a2c132f028ad…  2022-07-15T20:44:06.291   5799.67  test_aarch64-apple-darwin          https:
   9 │ default-macmini-aarch64-4.0  c7e2f9b4884b9f4177be4a0fd743c766…  2022-07-15T17:46:52.771   7253.23  test_aarch64-apple-darwin          https: ⋯
  10 │ default-amdci5.4             fd70eabc1dd6c79149edb82da9e9c37d…  2022-07-15T04:39:35.593   2676.27  test_x86_64-linux-musl             https:
  11 │ default-amdci4.1             85b895bb6919ea86d9b6201108af3a66…  2022-07-14T19:50:37.410   1310.48  test_x86_64-linux-gnuassertrr-net  https:
  12 │ default-macmini-aarch64-2.0  b3b229e2be9bb661ed0dbff525c7a9f2…  2022-07-14T15:51:10.999  10823.2   test_aarch64-apple-darwin          https:
  13 │ default-amdci4.2             201d4f6715c908b736d8552d27afd1aa…  2022-07-13T09:02:25.148   1309.31  test_x86_64-linux-gnuassertrr-net  https: ⋯
  14 │ default-amdci5.0             9629154b023de2b085b75fccb20c9a80…  2022-07-12T19:43:56.545   1673.96  test_i686-linux-gnu                https:
  15 │ default-amdci5.6             9629154b023de2b085b75fccb20c9a80…  2022-07-12T19:43:56.545   1591.82  test_x86_64-linux-musl             https:
  16 │ default-amdci5.2             511ea72aafdce1e00a5a39612c31fca6…  2022-07-12T08:13:07.168   1675.97  test_i686-linux-gnu                https:
  17 │ default-amdci5.7             0aeb0adba6ef3a90af4d958b3737c2ac…  2022-07-12T03:54:03.610   1880.59  test_i686-linux-gnu                https: ⋯
  18 │ default-amdci5.6             7be96ce1921265c088736959e2dec921…  2022-07-11T21:12:23.875  11859.3   test_x86_64-linux-gnuassertrr-net  https:
  19 │ default-macmini-aarch64-3.0  ba146fbf0b2ee736724e48dd1266be32…  2022-07-10T16:02:12.497   8059.57  test_aarch64-apple-darwin          https:
  20 │ default-amdci4.3             ba146fbf0b2ee736724e48dd1266be32…  2022-07-10T16:02:12.497   2962.92  test_x86_64-linux-gnu              https:
  21 │ default-amdci5.7             5a92bc80ea6dd74a7da4e9d361848a67…  2022-07-09T09:42:34.371   1532.11  test_x86_64-linux-gnu              https: ⋯
  22 │ default-amdci4.3             dd19c5ad980d5b0d231c6cd71c427ba8…  2022-07-06T20:40:24.876   2147.96  test_i686-linux-gnu                https:
  23 │ default-amdci4.1             301b62ae73e21a193d34fa8a312a913e…  2022-07-06T18:53:13.755   1301.42  test_x86_64-linux-gnuassertrr-net  https:
  24 │ default-macmini-aarch64-1.0  b73bf8618579d5ae0327917af590d823…  2022-07-06T12:32:55.235   2995.09  test_aarch64-apple-darwin          https:
  25 │ default-amdci5.7             22c6eea6b0d7a5b50420112406d3680c…  2022-07-06T12:31:28.434   1572.65  test_x86_64-linux-musl             https: ⋯
  26 │ default-amdci4.1             c5aa255280cba6ae389296c9efd4e80b…  2022-07-06T06:55:26.074   2361.38  test_x86_64-linux-musl             https:
  27 │ default-amdci5.4             7a21d52d4847a3ebed944888eae98b8c…  2022-07-06T06:33:49.789   1105.04  test_x86_64-linux-gnuassertrr-net  https:
  28 │ default-amdci5.6             7a21d52d4847a3ebed944888eae98b8c…  2022-07-06T06:33:49.789   2244.59  test_i686-linux-gnu                https:
  29 │ default-amdci5.0             3f4fc6307ac4fdf3ac84b2f804a8ed05…  2022-07-06T04:04:37.940   1490.6   test_x86_64-linux-gnu              https: ⋯
  30 │ default-amdci4.5             3f4fc6307ac4fdf3ac84b2f804a8ed05…  2022-07-06T04:04:37.940   2048.35  test_i686-linux-gnu                https:
  31 │ default-amdci4.1             3f4fc6307ac4fdf3ac84b2f804a8ed05…  2022-07-06T04:04:37.940   3373.71  test_x86_64-linux-musl             https:
  32 │ default-macmini-aarch64-4.0  c31be803ec99a98c890628890acdd944…  2022-07-05T18:37:55.271   9827.62  test_aarch64-apple-darwin          https:
  33 │ default-armageddon.5         f849517c9fb62bd63f33c4219abd20cf…  2022-06-26T16:19:17.575   3516.66  test_aarch64-linux-gnu             https: ⋯
                                                                                                                                    4 columns omitted
```

**Comment by staticfloat** [comment]
So it looks to me like we can't blame the CSAIL network for the `httpbingo.org/drip` failures, and we can't blame a single operating system.  :P

**Comment by timholy** [comment]
The grep is awesome. We could use it to compute the frequency of the failure ("occurs approximately 1 in every `n` runs" with a concrete value for `n`) and then give a likely commit range (say, including the first observation and going back 2n or 3n commits. That would make scanning the commit logs more pleasant.

**Pull request merged**
