### PR TITLE
Use a separate `upload_linux.arches` file to define the `upload_linux` build matrix (instead of re-using the `build_linux.arches` file)

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by staticfloat** [comment]
Yeah, I was lazy in trying to avoid this, but this is probably better.  I will note that I originally had tried to only upload to S3 if both the normal and RR builds were successful, but was unsuccessful in getting that to work properly.  We could come up with a way to do that now that we have better control over this, but I'm still not so concerned about that.

**Comment by staticfloat** [comment]
> It shows up as gray for me.

Huh, me as well.  I think it's because of the `depends_on` error.

**Comment by DilumAluthge** [comment]
I'll resign the pipelines.

**Comment by staticfloat** [comment]
BTW, there's a convenience `make sign_treehashes` target in this repository.

**Comment by DilumAluthge** [comment]
Where do I put the private key before I run `make sign_treehashes`? Right now I have it in the root of the `julia-buildkite` repo, and that doesn't seem to be working.

**Comment by DilumAluthge** [comment]
Here's my output from running `make sign_treehashes`:

```
Dilums-MBP:julia-buildkite dilum$ make sign_treehashes
cd .buildkite/cryptic_repo_root && sign_treehashes --repo-root=$(pwd) --verbose
Successfully parsed the following command-line arguments:

                       VERBOSE: true
        AGENT_PRIVATE_KEY_PATH: /var/folders/dg/7mtlrlqd6fz01jdb9djb33bm0000gp/T/tmp.c87wxH6p/julia-buildkite/agent_key
                     REPO_ROOT: /var/folders/dg/7mtlrlqd6fz01jdb9djb33bm0000gp/T/tmp.c87wxH6p/julia-buildkite/.buildkite/cryptic_repo_root



 -> Homebrew OpenSSL installation found at /usr/local/Cellar/openssl@3/3.0.2
The command rsautl was deprecated in version 3.0. Use 'pkeyutl' instead.
Searching for '.yml' files with the pattern '/var/folders/dg/7mtlrlqd6fz01jdb9djb33bm0000gp/T/tmp.c87wxH6p/julia-buildkite/.buildkite/cryptic_repo_root/.buildkite/**/*.yml'
  -> Found 14 .yml files
Extracting treehashes from '/var/folders/dg/7mtlrlqd6fz01jdb9djb33bm0000gp/T/tmp.c87wxH6p/julia-buildkite/.buildkite/cryptic_repo_root/.buildkite/pipelines/main/0_webui.yml'
Parsed out 0 pipelines being launched.
Extracting treehashes from '/var/folders/dg/7mtlrlqd6fz01jdb9djb33bm0000gp/T/tmp.c87wxH6p/julia-buildkite/.buildkite/cryptic_repo_root/.buildkite/pipelines/main/launch_signed_jobs.yml'
Parsed out 0 pipelines being launched.
Extracting treehashes from '/var/folders/dg/7mtlrlqd6fz01jdb9djb33bm0000gp/T/tmp.c87wxH6p/julia-buildkite/.buildkite/cryptic_repo_root/.buildkite/pipelines/main/launch_unsigned_builders.yml'
Parsed out 0 pipelines being launched.
Extracting treehashes from '/var/folders/dg/7mtlrlqd6fz01jdb9djb33bm0000gp/T/tmp.c87wxH6p/julia-buildkite/.buildkite/cryptic_repo_root/.buildkite/pipelines/main/misc/doctest.yml'
Parsed out 0 pipelines being launched.
Extracting treehashes from '/var/folders/dg/7mtlrlqd6fz01jdb9djb33bm0000gp/T/tmp.c87wxH6p/julia-buildkite/.buildkite/cryptic_repo_root/.buildkite/pipelines/main/misc/embedding.yml'
Parsed out 0 pipelines being launched.
Extracting treehashes from '/var/folders/dg/7mtlrlqd6fz01jdb9djb33bm0000gp/T/tmp.c87wxH6p/julia-buildkite/.buildkite/cryptic_repo_root/.buildkite/pipelines/main/misc/llvmpasses.yml'
Parsed out 0 pipelines being launched.
Extracting treehashes from '/var/folders/dg/7mtlrlqd6fz01jdb9djb33bm0000gp/T/tmp.c87wxH6p/julia-buildkite/.buildkite/cryptic_repo_root/.buildkite/pipelines/main/misc/sanitizers.yml'
Parsed out 0 pipelines being launched.
Extracting treehashes from '/var/folders/dg/7mtlrlqd6fz01jdb9djb33bm0000gp/T/tmp.c87wxH6p/julia-buildkite/.buildkite/cryptic_repo_root/.buildkite/pipelines/main/misc/whitespace.yml'
Parsed out 0 pipelines being launched.
Extracting treehashes from '/var/folders/dg/7mtlrlqd6fz01jdb9djb33bm0000gp/T/tmp.c87wxH6p/julia-buildkite/.buildkite/cryptic_repo_root/.buildkite/pipelines/main/platforms/build_linux.yml'
Parsed out 0 pipelines being launched.
Extracting treehashes from '/var/folders/dg/7mtlrlqd6fz01jdb9djb33bm0000gp/T/tmp.c87wxH6p/julia-buildkite/.buildkite/cryptic_repo_root/.buildkite/pipelines/main/platforms/test_linux.yml'
Parsed out 0 pipelines being launched.
Extracting treehashes from '/var/folders/dg/7mtlrlqd6fz01jdb9djb33bm0000gp/T/tmp.c87wxH6p/julia-buildkite/.buildkite/cryptic_repo_root/.buildkite/pipelines/main/platforms/upload_linux.yml'
Parsed out 0 pipelines being launched.
Extracting treehashes from '/var/folders/dg/7mtlrlqd6fz01jdb9djb33bm0000gp/T/tmp.c87wxH6p/julia-buildkite/.buildkite/cryptic_repo_root/.buildkite/pipelines/scheduled/0_webui.yml'
Parsed out 1 pipelines being launched.
signature_file '.buildkite/pipelines/scheduled/coverage/coverage_linux64.yml.signature' updated
Extracting treehashes from '/var/folders/dg/7mtlrlqd6fz01jdb9djb33bm0000gp/T/tmp.c87wxH6p/julia-buildkite/.buildkite/cryptic_repo_root/.buildkite/pipelines/scheduled/coverage/coverage_linux64.yml'
Parsed out 0 pipelines being launched.
Extracting treehashes from '/var/folders/dg/7mtlrlqd6fz01jdb9djb33bm0000gp/T/tmp.c87wxH6p/julia-buildkite/.buildkite/cryptic_repo_root/.buildkite/pipelines/scheduled/launch_unsigned_jobs.yml'
Parsed out 0 pipelines being launched.
```

**Comment by DilumAluthge** [comment]
@staticfloat Why did it not regenerate the `launch_signed_jobs.yml.signature` signature when I ran `make sign_treehashes`?

**Comment by staticfloat** [comment]
Try checking out the `sf/group_capable` branch of `cryptic`.

**Comment by DilumAluthge** [comment]
> Try checking out the `sf/group_capable` branch of `cryptic`.

Looks like that worked!

**Comment by DilumAluthge** [comment]
Is there an open PR for the `sf/group_capable` branch?

**Comment by staticfloat** [comment]
Not yet; I'm happy with some of the changes, but it can't quite deal with adding `depends_on` nodes properly yet.  I feel we need to move to something more reliable than `sed` for that; perhaps `shyaml` or `yq`.

**Pull request merged**
