### PR TITLE
Set the number of BLAS threads to 2.

### PR DESCRIPTION
**Pull request by gbaraldi**
As an experiment, I set the blas threads to 1, and enable threads on the matmul testset.

Ref #239 

Edit:
Set BLAS threads to 2 to reduce change of OOM on windows and reduce contention

### CODE REVIEW

**Comment by staticfloat** [comment]
Discussed this on the call, and we decided to set the number of threads to 2 everywhere.  That should solve our memory issues, and also exercise multithreading paths.

**Comment by gbaraldi** [comment]
Is this good to merge?

**Comment by DilumAluthge** [comment]
Can you update the PR title to reflect the final contents of the PR?

**Comment by staticfloat** [comment]
Don't merge this yet; I think Kristoffer and I have found that we are actually only supposed to be using one thread on CI.  I think we need to solve the timing issue in Distributed's setting of threads, first.

**Comment by gbaraldi** [comment]
So distributed should be passing the number of threads as 1 already? But doesn't?

**Comment by staticfloat** [comment]
https://github.com/JuliaLang/julia/pull/46844#issuecomment-1315790913

**Pull request closed without merging**
